name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version: ['26.1', '26.3', '27.2', '28.2', 'snapshot']
        cask_version: ['snapshot']

    steps:
    - name: Checkout org-gcal repo
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - uses: actions/cache@v4.2.3
      id: cache-cask-packages
      with:
        path: .cask
        key: cache-cask-packages-000

    - uses: actions/cache@v4.2.3
      id: cache-cask-executable
      with:
        path: ~/.cask
        key: cache-cask-executable-000

    - name: Install Cask
      uses: cask/setup-cask@master
      if: steps.cache-cask-executable.outputs.cache-hit != 'true'
      with:
        version: snapshot
    - run: echo "$HOME/.cask/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: make elpa

    - name: Compile
      run: make compile

    - name: Test
      run: make test

    - name: SSH into container on failure
      if: ${{ failure() }}
      uses: telotortium/action-upterm@wait-timeout-minutes
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        wait-timeout-minutes: 2
